CREATE OR REPLACE STORAGE INTEGRATION S3_INT_ECOMMERCE
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = '<AWS_IAM_ROLE_ARN>'
  STORAGE_ALLOWED_LOCATIONS = ('s3://<S3_BUCKET_NAME>/processed/');
