CREATE OR REPLACE WAREHOUSE WH_ECOMMERCE
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE ECOMMERCE_PIPELINE;
CREATE OR REPLACE SCHEMA ECOMMERCE_PIPELINE.RAW;
